import { Head, Link } from '@inertiajs/react';
import { ArrowLeft } from 'lucide-react';
import AgenceLayout from '../../../Layouts/AgenceLayout';
import { Badge } from '../../../components/ui/badge';
import { Button } from '../../../components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '../../../components/ui/card';
import { agenceButtonStyles } from '../../../lib/buttonStyles';
const money = (v) => `${new Intl.NumberFormat('fr-FR').format(Number(v || 0))} FCFA`;
export default function ImpayesDetail({ locataire, loyers = [], total = 0 }) { return <AgenceLayout title="Détail des impayés"><Head title={`Impayés - ${locataire.name}`} /><div className="mx-auto flex w-full max-w-6xl flex-col gap-6"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-semibold">{locataire.name}</h2><p className="text-sm text-slate-500">{locataire.code} · {locataire.tel1 || 'Téléphone non renseigné'}</p></div><Button asChild variant="outline" className={agenceButtonStyles.outline}><Link href="/agence/locataires/impayes"><ArrowLeft className="h-4 w-4" /> Retour</Link></Button></div><Card className="border-red-200 bg-red-50"><CardContent className="p-5"><p className="text-sm text-red-700">Total restant à payer</p><p className="text-2xl font-bold text-red-800">{money(total)}</p></CardContent></Card><Card className="rounded-2xl border-[#c8d4de]"><CardHeader><CardTitle className="text-base">Détail des échéances</CardTitle></CardHeader><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[800px] text-sm"><thead><tr className="border-y bg-slate-50 text-left text-xs uppercase text-slate-500">{['Période','Propriété','Porte','Attendu','Payé','Reste','Statut'].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{loyers.map(row=><tr key={row.id} className="border-b"><td className="px-4 py-3 font-medium">{row.periode}</td><td className="px-4 py-3">{row.propriete}</td><td className="px-4 py-3">{row.porte}</td><td className="px-4 py-3">{money(row.attendu)}</td><td className="px-4 py-3 text-emerald-700">{money(row.paye)}</td><td className="px-4 py-3 font-semibold text-red-700">{money(row.reste)}</td><td className="px-4 py-3"><Badge variant="outline">{row.statut}</Badge></td></tr>)}</tbody></table></CardContent></Card></div></AgenceLayout>; }
